-- 3595230's Lua and Manifest Generated by Solus Bot in Morrenus Games!
-- Call of Duty®: Modern Warfare® II
-- Generated: 2025-08-12 13:21:01
-- Total Depots: 18
-- Total DLCs: 4
-- Shared Depots: 1

-- MAIN APPLICATION
addappid(3595230) -- Call of Duty®: Modern Warfare® II
-- MAIN APP DEPOTS
addappid(3603196, 1, "5fa7fec1a1b49284c9c7a71339463561de33da4153ac0505e6ab4cc98302342e") -- Depot 3603196
setManifestid(3603196, "2478578705665376566", 25297918897)
addappid(3603197, 1, "0e3c160ee7cb0b60222663b089596cfff8ebb8fac721d8dffae7344f8da77a55") -- Depot 3603197
setManifestid(3603197, "3394223495559782177", 786671157)
addappid(3603198, 1, "b2b665208413b45c729645b2674090159ecebf4d43676456e7ec98427ff6a020") -- Depot 3603198
setManifestid(3603198, "8957710439420083405", 2134235240)
addappid(3603215, 1, "cfbe70a2765fd23fc9e18fc709477bc89b613a9dbe33e963b958f02d5bf580c7") -- Depot 3603215
setManifestid(3603215, "5797612927145053079", 31859324)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
-- DLCS WITH DEDICATED DEPOTS
-- Call of Duty Modern Warfare II - Campaign (AppID: 3602840)
addappid(3602840)
addappid(3602840, 1, "9f6de3e5b29ab7ba7f72305d430f9935a052a51abd13178982074fd89d8bbb07") -- Call of Duty Modern Warfare II - Campaign - Depot 3602840
setManifestid(3602840, "5389317900021246171", 24963065240)
addappid(3595232, 1, "86bf4f331b149631dec1cb4743ef216c7f60c9e39e6cc5dfd1484dc86f3f9c3a") -- Call of Duty Modern Warfare II - Campaign - Depot 3595232
setManifestid(3595232, "6495836662819384127", 474363976)
addappid(3595233, 1, "517fcd348526034a9b52aff71df25f457b38f3650243811b7ba7cf2fe5961278") -- Call of Duty Modern Warfare II - Campaign - Depot 3595233
setManifestid(3595233, "1401089134170976246", 841955392)
addappid(3602849, 1, "d3787b66085d81234340db85b95f5523d45dca0c41afb752c40355c27755ef46") -- Call of Duty Modern Warfare II - Campaign - Depot 3602849
setManifestid(3602849, "495131983024490472", 24498252)
-- Call of Duty Modern Warfare II - Multiplayer (AppID: 3602850)
addappid(3602850)
addappid(3602850, 1, "9b696e7b45cfb8511760c5c654b6563b69638d35145c833e022be1228fb78dc7") -- Call of Duty Modern Warfare II - Multiplayer - Depot 3602850
setManifestid(3602850, "7170228761444113903", 19058346872)
addappid(3602854, 1, "e9340c8a10ff26d2477387f54cc4af1482f4cb37a6fc46d3a6e153c37e702b71") -- Call of Duty Modern Warfare II - Multiplayer - Depot 3602854
setManifestid(3602854, "7134251492112591067", 3810944)
addappid(3602971, 1, "4022998b07d9a59f1763b225802dc27260e9277abbf6dd7406054da4c3f8f14a") -- Call of Duty Modern Warfare II - Multiplayer - Depot 3602971
setManifestid(3602971, "5643052353120217765", 3896596)
-- Call of Duty Modern Warfare II - Co-op (AppID: 3602860)
addappid(3602860)
addappid(3602860, 1, "612d9407fb1b2aad0b5cc0f325141b0de471397636c901e9f732c9398e662381") -- Call of Duty Modern Warfare II - Co-op - Depot 3602860
setManifestid(3602860, "2063298751918385591", 7747460984)
addappid(3602975, 1, "cfcf4f0ca0f42ea5a422d80f0b3f754b71048680f1306229059adc8f86becf6b") -- Call of Duty Modern Warfare II - Co-op - Depot 3602975
setManifestid(3602975, "2610206585314935997", 371779656)
addappid(3603171, 1, "8e776840849b36e68e72caf38b4749482bfac0c930021d671a2085db69755e33") -- Call of Duty Modern Warfare II - Co-op - Depot 3603171
setManifestid(3603171, "9031206097584138907", 3307456)
-- Call of Duty Modern Warfare II - DMZ Beta (AppID: 3602970)
addappid(3602970)
addappid(3602970, 1, "f1281334c302cae2aff8688bdcf799fad6fdb5ba746ff190decb3084ecb11366") -- Call of Duty Modern Warfare II - DMZ Beta - Depot 3602970
setManifestid(3602970, "425819475588124927", 9955064808)
addappid(3603176, 1, "f99755c93ad43b98fe8c48c49cbeae75cf4ca41b01c390f8b2eb53e04744d4e2") -- Call of Duty Modern Warfare II - DMZ Beta - Depot 3603176
setManifestid(3603176, "7034086291068148606", 195144340)
addappid(3603193, 1, "0cc23692923ca492f15c763f7ea7ae3c563cb0db6da27bed9c8903d1d751a829") -- Call of Duty Modern Warfare II - DMZ Beta - Depot 3603193
setManifestid(3603193, "7557123764704027015", 1542348)